//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllDeptsAllProductsAllData
    {
        public double Article { get; set; }
        public string Article_Description { get; set; }
        public Nullable<double> Barcode { get; set; }
        public string Storage_Bin { get; set; }
        public string Department { get; set; }
        public string Sub_Department { get; set; }
    }
}
