//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductLocationsActualEntities : DbContext
    {
        public ProductLocationsActualEntities()
            : base("name=ProductLocationsActualEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BeerBarcode> BeerBarcodes { get; set; }
        public virtual DbSet<BeerData> BeerDatas { get; set; }
        public virtual DbSet<ProductsWithBarcode> ProductsWithBarcodes { get; set; }
        public virtual DbSet<ProductsWithData> ProductsWithDatas { get; set; }
        public virtual DbSet<AllDeptsAllProductsAllData> AllDeptsAllProductsAllDatas { get; set; }
        public virtual DbSet<BeerAllProductsAllData> BeerAllProductsAllDatas { get; set; }
        public virtual DbSet<GroceryAllProductsAllData> GroceryAllProductsAllDatas { get; set; }
    }
}
