//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryEntityTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroceryBarcode
    {
        public double Article { get; set; }
        public string Product_Description { get; set; }
        public Nullable<double> Barcode { get; set; }
    }
}
