//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryEntityTest.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GroceryTestDBEntities : DbContext
    {
        public GroceryTestDBEntities()
            : base("name=GroceryTestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BeerBarcode> BeerBarcodes { get; set; }
        public virtual DbSet<BeerData> BeerDatas { get; set; }
        public virtual DbSet<DairyBarcode> DairyBarcodes { get; set; }
        public virtual DbSet<DairyData> DairyDatas { get; set; }
        public virtual DbSet<FrozenBarcode> FrozenBarcodes { get; set; }
        public virtual DbSet<FrozenData> FrozenDatas { get; set; }
        public virtual DbSet<GMBarcode> GMBarcodes { get; set; }
        public virtual DbSet<GMData> GMDatas { get; set; }
        public virtual DbSet<GroceryBarcode> GroceryBarcodes { get; set; }
        public virtual DbSet<GroceryData> GroceryDatas { get; set; }
        public virtual DbSet<WineBarcode> WineBarcodes { get; set; }
        public virtual DbSet<WineData> WineDatas { get; set; }
        public virtual DbSet<BeerAllProductsAllData> BeerAllProductsAllDatas { get; set; }
        public virtual DbSet<DairyAllProductsAllData> DairyAllProductsAllDatas { get; set; }
        public virtual DbSet<FrozenAllProductsAllData> FrozenAllProductsAllDatas { get; set; }
        public virtual DbSet<GMAllProductsAllData> GMAllProductsAllDatas { get; set; }
        public virtual DbSet<GroceryAllProductsAllData> GroceryAllProductsAllDatas { get; set; }
        public virtual DbSet<WineAllProductsAllData> WineAllProductsAllDatas { get; set; }
        public virtual DbSet<AllDeptsAllProductsAllData> AllDeptsAllProductsAllDatas { get; set; }
    }
}
